Create component gpio_evaluateSwitch
- Copy library written for avr projects
- Modify files to work with esp32 instead of avr
- create component for esp-idf (CMakeLists.txt)

Note this broke the `make` command when including this library " fatal
error: gpio_evaluateSwitch.hpp: No such file or directory"
However `idf.py` works fine